;;; Automatically generated by ‘recentf’ on Sun Oct 17 13:17:33 2021.

(setq recentf-list
      '(
        "/Users/zhenhuawang/.emacs.d/emacs.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
