;;; Automatically generated by ‘recentf’ on Sun Oct 17 11:57:21 2021.

(setq recentf-list
      '(
        "/Users/zhenhuawang/.emacs.d/elpa/pdf-tools-20211004.514/build/server/configure.ac"
        "/Users/zhenhuawang/.emacs.d/elpa/pdf-tools-20211004.514/build/server/configure"
        "/Volumes/WORKSPACE/Dotfiles/.emacs.d/elpa/pdf-tools-20211004.514/build/server/synctex_parser.h"
        "/Volumes/WORKSPACE/Dotfiles/.emacs.d/emacs.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
