;;; Automatically generated by ‘recentf’ on Sun Oct 17 02:56:50 2021.

(setq recentf-list
      '(
        "/home/zhenhua/Workspace/test/hw8.pdf"
        "/home/zhenhua/.emacs.d/emacs.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
